// import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/Provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// const inter = Inter({ subsets: ["latin"] });
import { Lexend } from 'next/font/google';

const poppins = Lexend({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

// TODO:  I have to update the metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} >
      <NextAuthProvider>             
       <Header/>
        {children}
        <Footer/>     
      </NextAuthProvider>
        </body>
    </html>
  );
}
